cicd:test4

diff --git a/deployment_configuration.yaml b/deployment_configuration.yaml
--- a/deployment_configuration.yaml
+++ b/deployment_configuration.yaml
@@ -10,11 +10,16 @@ files:
 steps:
   - stepType: Command
     name: Extract and Run Deploy Script
-    runAs: root
+    runAs: ubuntu
     timeoutInSeconds: 300
     command: |
       set -euxo pipefail
       cd /home/ubuntu/deploy_workspace
       tar -xzf nodejs-janus-app.tar.gz
-      chmod +x deploy.sh
-      ./deploy.sh
+      if [ -f deploy.sh ]; then
+        chmod +x deploy.sh
+        ./deploy.sh
+      else
+        echo "❌ deploy.sh not found!"
+        exit 1
+      fi
